package Entities;
// Generated Apr 30, 2016 10:57:34 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Phonecontact generated by hbm2java
 */
@Entity
@Table(name="phonecontact"
    ,catalog="contact"
)
public class Phonecontact  implements java.io.Serializable {


     private String name;
     private long number;

    public Phonecontact() {
    }

    public Phonecontact(String name, long number) {
       this.name = name;
       this.number = number;
    }
   
     @Id 

    
    @Column(name="Name", unique=true, nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Number", nullable=false)
    public long getNumber() {
        return this.number;
    }
    
    public void setNumber(long number) {
        this.number = number;
    }




}


